const mongoose = require('mongoose');

function generateSimpleCode(length = 6) {
    // This is a basic, reliable code generator. Use nanoid for better assurance.
    const characters = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; 
    let code = '';
    for (let i = 0; i < length; i++) {
        code += characters.charAt(Math.floor(Math.random() * characters.length));
    }
    return code;
}

const UserSchema = new mongoose.Schema({
    // Primary identifier, generated by MongoDB, replacing manual userId
    
    email: { 
        type: String,
        required: true,
        unique: true
    },
    password: { 
        type: String,
        required: true
    },
    firstName: { 
        type: String,
        required: true
    },
    lastName: {
        type: String,
        required: true
    },
    phoneNumber: { 
        type: String,
        required: true
    },
    address: { 
        type: String,
        required: true
    },
    role: {
        type: String,
        enum: ['user', 'admin'], // Only these two values are allowed
        default: 'user'
    },
    //  uniqueCode: {
    //     type: String,
    //     unique: true,
    //     uppercase: true,
    //     index: true,
    // },
    date: {
        type: Date,
        default: Date.now
    }
});



module.exports = mongoose.model('User', UserSchema);